server:
  port: 3009
spring:
  application:
    name: GatewayService
  cloud:
    gateway:
      routes:
      - id: FlightServer
        uri: http://localhost:3007/
        predicates:
        - Path=/flight/**
      - id: AirportService
        uri: http://localhost:3010/
        predicates:
        - Path=/airport/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  registerWithEureka:
       - true
  fetchRegistry:
       - true